import psycopg2


def account_script(cur: psycopg2.extensions.cursor):
    script = """
        CREATE TABLE IF NOT EXISTS accounts
        (
            customer_id INTEGER NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
            first_name  VARCHAR(30),
            last_name   VARCHAR(30),
            address_1   VARCHAR(255),
            address_2   VARCHAR(255),
            city        VARCHAR(30),
            state       VARCHAR(30),
            zip_code    VARCHAR(10),
            join_date   DATE
        );

        CREATE INDEX IF NOT EXISTS idx_accounts_account_name
            ON accounts (first_name, last_name);
    """
    cur.execute(script)


def product_script(cur: psycopg2.extensions.cursor):
    script = """
        CREATE TABLE IF NOT EXISTS products
        (
            product_id INTEGER NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
            product_code  VARCHAR(10),
            product_description   VARCHAR(50)
        );

        CREATE INDEX IF NOT EXISTS idx_products_product_code
            ON products (product_code);
        """
    cur.execute(script)


def transaction_script(cur: psycopg2.extensions.cursor):
    script = """
        CREATE TABLE IF NOT EXISTS transactions
        (
            transaction_id   VARCHAR NOT NULL PRIMARY KEY,
            transaction_date DATE,
            product_id       INTEGER,
            product_code VARCHAR(10),
            product_description VARCHAR(50),
            quantity SMALLINT,
            account_id INTEGER,
            FOREIGN KEY (product_id) REFERENCES products(product_id),
            FOREIGN KEY (account_id) REFERENCES accounts(customer_id)
        );

        CREATE INDEX IF NOT EXISTS idx_transaction_product_code
            ON transactions (product_code);
    """
    cur.execute(script)


def insert(cur: psycopg2.extensions.cursor, conn: psycopg2.extensions.connection):
    tables = ["accounts", "products", "transactions"]
    for tabel in tables:
        with open(f"/app/data/{tabel}.csv", "r") as file:
            cur.copy_expert(f"""
                COPY {tabel} FROM STDIN WITH (FORMAT CSV, HEADER TRUE);
            """, file)

        conn.commit()


def main():
    host = "postgres"
    database = "postgres"
    user = "postgres"
    pas = "postgres"
    with psycopg2.connect(host=host, database=database, user=user, password=pas) as conn:
        cur = conn.cursor()

        account_script(cur)
        product_script(cur)
        transaction_script(cur)
        conn.commit()

        insert(cur, conn)

if __name__ == "__main__":
    main()
