import psycopg2
import csv


def account_script(cur: psycopg2.extensions.cursor):
    script = """
        CREATE TABLE IF NOT EXISTS account
        (
            customer_id INTEGER NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
            first_name  VARCHAR(30),
            last_name   VARCHAR(30),
            address_1   VARCHAR(255),
            address_2   VARCHAR(255),
            city        VARCHAR(30),
            state       VARCHAR(30),
            zip_code    VARCHAR(10),
            join_date   DATE
        );

        CREATE INDEX idx_name
            ON account (first_name, last_name);
    """
    cur.execute(script)


def product_script(cur: psycopg2.extensions.cursor):
    script = """
        CREATE TABLE IF NOT EXISTS product
        (
            product_id INTEGER NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
            product_code  VARCHAR(10),
            product_description   VARCHAR(50),
        );

        CREATE INDEX idx_product_code
            ON product (product_code);
        """
    cur.execute(script)


def transaction_script(cur: psycopg2.extensions.cursor):
    script = """
        CREATE TABLE IF NOT EXISTS transaction
        (
            transaction_id   INTEGER NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
            transaction_date DATE,
            product_id       INTEGER,
            product_code VARCHAR(10),
            product_description VARCHAR(50),
            quantity SMALLINT,
            account_id INTEGER,
            FOREIGN KEY (product_id) REFERENCES product(product_id),
            FOREIGN KEY (account_id) REFERENCES account(customer_id)
        );

        CREATE INDEX idx_product
            ON transaction (product_code);

        CREATE INDEX idx_account
            ON transaction (account_id);
    """
    cur.execute(script)


def insert(cur: psycopg2.extensions.cursor, conn: psycopg2.extensions.connection):
    tables = ["accounts", "products", "transactions"]
    path = "./data"
    for table in tables:
        with open(path + "/" + table + ".csv") as file:
            reader = csv.reader(file)
            insert_query = ""
            values = []
            for i, row in enumerate(reader):
                if i == 0:
                    columns = ",".join(row)
                    placeholder = ", ".join(["%s"] * len(row))
                    insert_query = f"insert into {table[:-1]} ({columns}) values ({placeholder})"
                else:
                    values.append(tuple(row))

            cur.executemany(insert_query, values)
            conn.commit()


def main():
    host = "postgres"
    database = "postgres"
    user = "postgres"
    pas = "postgres"
    conn = psycopg2.connect(host=host, database=database, user=user, password=pas)
    cur = conn.cursor()

    account_script(cur); account_script(cur); transaction_script(cur)
    insert(cur, conn)

if __name__ == "__main__":
    main()
